name: evchargerapp
description: "Ev Plug EV Application"
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  geolocator: ^13.0.2
  http: ^1.2.0
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
