import 'package:flutter/foundation.dart';

enum AppLanguage { mn, en }

/// App-wide language selection.
///
/// This is a [ValueNotifier] so switching it rebuilds the whole app. It used to
/// be a bare static field, so a toggle only refreshed the screen it was on and
/// looked like it did nothing.
class LanguageController {
  LanguageController._();

  static final ValueNotifier<AppLanguage> language = ValueNotifier<AppLanguage>(
    AppLanguage.mn,
  );

  static AppLanguage get current => language.value;

  static void toggle() => language.value = language.value == AppLanguage.mn
      ? AppLanguage.en
      : AppLanguage.mn;

  static void set(AppLanguage value) => language.value = value;
}

class AppStrings {
  static AppLanguage get currentLanguage => LanguageController.current;

  static set currentLanguage(AppLanguage value) =>
      LanguageController.set(value);

  static const Map<String, Map<String, String>> _localizedValues = {
    'mn': {
      'appName': 'Zev Charger',
      'tagline': 'Монголын Анхны Сүлжээ Цэнэглэгч',
      'slideshow1_title': 'Улаанбаатар хотын EV Цэнэглэгч',
      'slideshow1_sub': 'Хамгийн хурдан 200 кВт хүртэлх супер цэнэглэгч',
      'slideshow2_title': 'Ухаалаг & Хялбар Төлбөр',
      'slideshow2_sub': 'QR код уншуулаад QPay / Картаар шууд төлнө',
      'login': 'Нэвтрэх',
      'register': 'Бүртгүүлэх',
      'phone_email': 'Утасны дугаар эсвэл И-мэйл',
      'password': 'Нууц үг',
      'forgot_password': 'Нууц үг мартсан?',
      'logout': 'Гарах',
      'activity_title': 'Үйл ажиллагаа',
      'activity_subtitle': 'Цэнэглэлтийн түүх',
      'activity_empty': 'Одоогоор бүртгэл алга байна',
      'activity_details': 'Техникийн мэдээлэл',
      'act_authorize': 'Эрх баталгаажлаа',
      'act_start': 'Цэнэглэлт эхэллээ',
      'act_stop': 'Цэнэглэлт дууслаа',
      'act_meter': 'Хэмжилт бүртгэгдлээ',
      'act_status': 'Төлөв шинэчлэгдлээ',
      'act_heartbeat': 'Холболт шалгагдлаа',
      'act_boot': 'Станц холбогдлоо',
      'act_remote_start': 'Алсаас эхлүүллээ',
      'act_remote_stop': 'Алсаас зогсоолоо',
      'act_reserve': 'Захиалга бүртгэгдлээ',
      'act_other': 'Станцын үйлдэл',
      'clear_history': 'Түүх цэвэрлэх',
      'media_artist': 'Ардын хөгжмийн чуулга',
      'media_track': 'Шангри-Ла аялгуу',
      'media_system': 'Dolby Atmos систем',
      'download_receipt': 'БАРИМТ',
      'done': 'БОЛСОН',
      'outside_temp': 'Гадаа агаарын хэм',
      'tx_ref': 'Гүйлгээний дугаар',
      'connector_speed': 'Залгуур / Хурд',
      'receipt_emailed': 'И-мэйлээр баримт илгээгдлээ.',
      'total_paid': 'Нийт Төлөгдсөн Дүн',
      'total_cost': 'Нийт төлбөр',
      'unit_price': 'Нэгжийн үнэ',
      'added_range': 'Нэмэгдэх зай',
      'last_measured': 'Сүүлийн хэмжилт',
      'estimated_total': 'Тооцоолсон дүн',
      'payment_ok': 'Төлбөр амжилттай! Цэнэглэж эхэллээ',
      'confirm_payment': 'Төлбөр баталгаажуулах',
      'scanning': 'УНШИЖ БАЙНА...',
      'vehicle_location': 'Улаанбаатар дахь автомашины байршил',
      'vehicle_location_hint': 'Дарж интерактив зураг нээх',
      'limit_label': 'Хязгаар',
      'charging_now': 'ЦЭНЭГЛЭЖ БАЙНА',
      'stop_charging': 'ЦЭНЭГЛЭЛТИЙГ ЗОГСООХ',
      'windows_locked': 'Цонх цоожтой',
      'slide_to_start': 'Цэнэглэж эхлэхийн тулд гулсуулна уу',
      'slide_default': 'Эхлүүлэхийн тулд гулсуулна уу',
      'charging_receipt': 'Цэнэглэлтийн Баримт',
      'set_charge_limit': 'Цэнэглэх Хязгаар Тохируулах',
      'charging_station': 'Цэнэглэх станц',
      'charge_limit': 'Цэнэглэх хязгаар',
      'energy_delivered': 'Шилжүүлсэн эрчим хүч',
      'time_remaining': 'Үлдсэн хугацаа',
      'ocpp_log': 'OCPP лог',
      'nav_stations': 'Станц',
      'search_stations': 'Улаанбаатар дахь цэнэглэгч хайх...',
      'start_route': 'ЧИГЛЭЛ ЭХЛҮҮЛЭХ',
      'stop_route': 'ЧИГЛЭЛ ЗОГСООХ',
      'route_loading': 'Замыг тооцоолж байна...',
      'route_unavailable': 'Замын мэдээлэл авах боломжгүй. Чиглэлээр удирдана.',
      'navigating': 'НАВИГАЦИ ЯВАГДАЖ БАЙНА',
      'arrived_full': 'Цэнэглэх станцад хүрч ирлээ! QR кодыг уншуулна уу.',
      'arrived_short': 'Та очих газартаа ирлээ',
      'getting_directions': 'Чиглэл авч байна',
      'map_title': 'Цэнэглэх станцын зураг',
      'back': 'Буцах',
      'available': 'Сул байна',
      'kw_super': 'кВт Супер',
      'unit_km': 'км',
      'unit_kw': 'кВт',
      'unit_m': 'м',
      'unit_kmh': 'км/ц',
      'toward': 'чиглэлд',
      'dir_n': 'хойш',
      'dir_ne': 'зүүн хойш',
      'dir_e': 'зүүн',
      'dir_se': 'зүүн урагш',
      'dir_s': 'урагш',
      'dir_sw': 'баруун урагш',
      'dir_w': 'баруун',
      'dir_nw': 'баруун хойш',
      'logout_title': 'Гарах уу?',
      'logout_body': 'Та бүртгэлээсээ гарна. Дахин нэвтрэх шаардлагатай.',
      'cancel': 'Цуцлах',
      'light_mode': 'Гэрэлтэй горим',
      'theme_dark_on': 'Бараан горим асаалаа',
      'theme_dark_off': 'Гэрэлтэй горим асаалаа',
      'or_login_with': 'Эсвэл дараах хаягаар нэвтрэх',
      'dont_have_account': 'Хаяггүй юу? Бүртгүүлэх',
      'already_have_account': 'Бүртгэлтэй юу? Нэвтрэх',
      'home': 'Нүүр',
      'stations': 'Станцууд',
      'map': 'Газрын зураг',
      'quick_controls': 'Түргэн удирдлага',
      'battery': 'Батерей',
      'remaining_km': 'Үлдсэн зайн хэмжээ',
      'charging': 'Цэнэглэж байна',
      'idle': 'Бэлэн',
      'scan_qr': 'QR код уншуулах',
      'ready_to_charge': 'Цэнэглэхэд бэлэн үү?',
      'scan_qr_desc': 'Цэнэглэгч дээрх QR кодыг уншуулж холбогдоно уу',
      'scan_button': 'QR КОД УНШУУЛАХ',
      'nearby_stations': 'Улаанбаатар дахь цэнэглэх станцууд',
      'power': 'Чадал',
      'vmax': 'Дээд хурд',
      'range': 'Зайн хэмжээ',
      'locked': 'Түгжигдсэн',
      'unlocked': 'Онгойлгосон',
      'dark': 'Бараан горим',
      'honk': 'Дохио өгөх',
      'control': 'Удирдлага',
      'energy': 'Эрчим хүч',
      'climate': 'Агааржуулагч',
      'media': 'Хөгжим',
      'tire_pressure': 'Дугуйн даралт',
      'location': 'Байршил',
      'last_known_location': 'Автомашины сүүлчийн байршил',
      'pay_and_start': '₮ ТӨЛӨӨД ЦЭНЭГЛЭЖ ЭХЛЭХ',
      'select_deposit': 'Цэнэглэх мөнгөн дүнг сонгоно уу:',
      'payment_method': 'Төлбөрийн хэрэгсэл:',
      'qpay': 'QPay (Үндэсний цахим төлбөр)',
      'card': 'Банкны карт (Голомт, Хаан)',
    },
    'en': {
      'appName': 'Zev Charger',
      'tagline': 'Mongolia\'s Premier EV Charging Network',
      'slideshow1_title': 'Ulaanbaatar Fast Chargers',
      'slideshow1_sub': 'Ultra-fast chargers up to 200 kW in UB',
      'slideshow2_title': 'Smart & Seamless Payment',
      'slideshow2_sub': 'Scan QR Code and pay instantly via QPay or Card',
      'login': 'Login',
      'register': 'Register',
      'phone_email': 'Phone Number or Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'logout': 'Log out',
      'activity_title': 'Activity',
      'activity_subtitle': 'Your charging history',
      'activity_empty': 'Nothing recorded yet',
      'activity_details': 'Technical details',
      'act_authorize': 'Authorised',
      'act_start': 'Charging started',
      'act_stop': 'Charging finished',
      'act_meter': 'Meter reading recorded',
      'act_status': 'Status updated',
      'act_heartbeat': 'Connection checked',
      'act_boot': 'Station connected',
      'act_remote_start': 'Started remotely',
      'act_remote_stop': 'Stopped remotely',
      'act_reserve': 'Reservation recorded',
      'act_other': 'Station event',
      'clear_history': 'Clear history',
      'media_artist': 'Folk Music Ensemble',
      'media_track': 'Shangri-La Melody',
      'media_system': 'Dolby Atmos system',
      'download_receipt': 'RECEIPT',
      'done': 'DONE',
      'outside_temp': 'Outside temperature',
      'tx_ref': 'Transaction ref',
      'connector_speed': 'Connector / Speed',
      'receipt_emailed': 'Receipt sent by email.',
      'total_paid': 'Total Paid',
      'total_cost': 'Total cost',
      'unit_price': 'Unit price',
      'added_range': 'Added range',
      'last_measured': 'Last measured',
      'estimated_total': 'Estimated total',
      'payment_ok': 'Payment complete. Charging started',
      'confirm_payment': 'Confirm payment',
      'scanning': 'SCANNING...',
      'vehicle_location': 'Vehicle location in Ulaanbaatar',
      'vehicle_location_hint': 'Tap to open the interactive map',
      'limit_label': 'Limit',
      'charging_now': 'CHARGING',
      'stop_charging': 'STOP CHARGING',
      'windows_locked': 'Windows locked',
      'slide_to_start': 'Slide to start charging',
      'slide_default': 'Slide to start',
      'charging_receipt': 'Charging Receipt',
      'set_charge_limit': 'Set Charge Limit',
      'charging_station': 'Charging station',
      'charge_limit': 'Charge limit',
      'energy_delivered': 'Energy delivered',
      'time_remaining': 'Time remaining',
      'ocpp_log': 'OCPP log',
      'nav_stations': 'Stations',
      'search_stations': 'Search chargers in Ulaanbaatar...',
      'start_route': 'START ROUTE',
      'stop_route': 'STOP ROUTE',
      'route_loading': 'Calculating route...',
      'route_unavailable': 'Road route unavailable. Guiding by direction.',
      'navigating': 'NAVIGATING',
      'arrived_full': 'You have arrived. Scan the QR code to begin.',
      'arrived_short': 'You have arrived',
      'getting_directions': 'Getting directions',
      'map_title': 'Charging station map',
      'back': 'Back',
      'available': 'available',
      'kw_super': 'kW Super',
      'unit_km': 'km',
      'unit_kw': 'kW',
      'unit_m': 'm',
      'unit_kmh': 'km/h',
      'toward': 'to the',
      'dir_n': 'north',
      'dir_ne': 'north-east',
      'dir_e': 'east',
      'dir_se': 'south-east',
      'dir_s': 'south',
      'dir_sw': 'south-west',
      'dir_w': 'west',
      'dir_nw': 'north-west',
      'logout_title': 'Log out?',
      'logout_body': 'You will be signed out and need to log in again.',
      'cancel': 'Cancel',
      'light_mode': 'Light Mode',
      'theme_dark_on': 'Dark mode on',
      'theme_dark_off': 'Light mode on',
      'or_login_with': 'Or continue with',
      'dont_have_account': 'Don\'t have an account? Register',
      'already_have_account': 'Already registered? Login',
      'home': 'Home',
      'stations': 'Stations',
      'map': 'Map',
      'quick_controls': 'Quick Controls',
      'battery': 'Battery',
      'remaining_km': 'Remaining Range',
      'charging': 'Charging',
      'idle': 'Standby',
      'scan_qr': 'Scan QR Code',
      'ready_to_charge': 'Ready to Charge?',
      'scan_qr_desc': 'Scan the station QR code to unlock plug & pay',
      'scan_button': 'SCAN QR CODE & START',
      'nearby_stations': 'Charging Stations in Ulaanbaatar',
      'power': 'Power',
      'vmax': 'Vmax',
      'range': 'Range',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'dark': 'Dark Mode',
      'honk': 'Sound Horn',
      'control': 'Controls',
      'energy': 'Energy',
      'climate': 'Climate',
      'media': 'Media',
      'tire_pressure': 'Tire Pressure',
      'location': 'Location',
      'last_known_location': 'Vehicle\'s Last Known Location',
      'pay_and_start': 'PAY & START CHARGING',
      'select_deposit': 'Select Charging Amount:',
      'payment_method': 'Payment Method:',
      'qpay': 'QPay (National Mobile Pay)',
      'card': 'Bank Card (Golomt / Khan Bank)',
    },
  };

  static String get(String key) {
    final langCode = currentLanguage == AppLanguage.mn ? 'mn' : 'en';
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
