import 'package:flutter/foundation.dart';

enum AppLanguage { mn, en }

/// How a language is shown in a switcher.
///
/// The flag stands in for the two-letter code: it reads at a glance and needs
/// no translating. The [label] is what screen readers announce, since a flag
/// emoji on its own says nothing useful.
extension AppLanguagePresentation on AppLanguage {
  String get flag => this == AppLanguage.mn ? '🇲🇳' : '🇬🇧';

  String get label => this == AppLanguage.mn ? 'Монгол' : 'English';
}

/// App-wide language selection.
///
/// This is a [ValueNotifier] so switching it rebuilds the whole app. It used to
/// be a bare static field, so a toggle only refreshed the screen it was on and
/// looked like it did nothing.
class LanguageController {
  LanguageController._();

  static final ValueNotifier<AppLanguage> language = ValueNotifier<AppLanguage>(
    AppLanguage.mn,
  );

  static AppLanguage get current => language.value;

  static void toggle() => language.value = language.value == AppLanguage.mn
      ? AppLanguage.en
      : AppLanguage.mn;

  static void set(AppLanguage value) => language.value = value;
}

class AppStrings {
  static AppLanguage get currentLanguage => LanguageController.current;

  static set currentLanguage(AppLanguage value) =>
      LanguageController.set(value);

  static const Map<String, Map<String, String>> _localizedValues = {
    'mn': {
      'appName': 'Eplug',
      'tagline': 'Монголын Анхны Сүлжээ Цэнэглэгч',
      'slideshow1_title': 'Улаанбаатар хотын EV Цэнэглэгч',
      'slideshow1_sub': 'Хамгийн хурдан 200 кВт хүртэлх супер цэнэглэгч',
      'slideshow2_title': 'Ухаалаг & Хялбар Төлбөр',
      'slideshow2_sub': 'QR код уншуулаад QPay / Картаар шууд төлнө',
      'login': 'Нэвтрэх',
      'register': 'Бүртгүүлэх',
      'logout': 'Гарах',
      'activity_title': 'Үйл ажиллагаа',
      'activity_subtitle': 'Цэнэглэлтийн түүх',
      'activity_empty': 'Одоогоор бүртгэл алга байна',
      'activity_details': 'Техникийн мэдээлэл',
      'act_authorize': 'Эрх баталгаажлаа',
      'act_start': 'Цэнэглэлт эхэллээ',
      'act_stop': 'Цэнэглэлт дууслаа',
      'act_meter': 'Хэмжилт бүртгэгдлээ',
      'act_status': 'Төлөв шинэчлэгдлээ',
      'act_heartbeat': 'Холболт шалгагдлаа',
      'act_boot': 'Станц холбогдлоо',
      'act_remote_start': 'Алсаас эхлүүллээ',
      'act_remote_stop': 'Алсаас зогсоолоо',
      'act_reserve': 'Захиалга бүртгэгдлээ',
      'act_other': 'Станцын үйлдэл',
      'clear_history': 'Түүх цэвэрлэх',
      'media_artist': 'Ардын хөгжмийн чуулга',
      'media_track': 'Шангри-Ла аялгуу',
      'media_system': 'Dolby Atmos систем',
      'download_receipt': 'БАРИМТ',
      'done': 'БОЛСОН',
      'outside_temp': 'Гадаа агаарын хэм',
      'tx_ref': 'Гүйлгээний дугаар',
      'connector_speed': 'Залгуур / Хурд',
      'receipt_emailed': 'И-мэйлээр баримт илгээгдлээ.',
      'total_paid': 'Нийт Төлөгдсөн Дүн',
      'total_cost': 'Нийт төлбөр',
      'unit_price': 'Нэгжийн үнэ',
      'added_range': 'Нэмэгдэх зай',
      'last_measured': 'Сүүлийн хэмжилт',
      'estimated_total': 'Тооцоолсон дүн',
      'payment_ok': 'Төлбөр амжилттай! Цэнэглэж эхэллээ',
      'confirm_payment': 'Төлбөр баталгаажуулах',
      'scanning': 'УНШИЖ БАЙНА...',
      'vehicle_location': 'Улаанбаатар дахь автомашины байршил',
      'vehicle_location_hint': 'Дарж интерактив зураг нээх',
      'limit_label': 'Хязгаар',
      'charging_now': 'ЦЭНЭГЛЭЖ БАЙНА',
      'stop_charging': 'ЦЭНЭГЛЭЛТИЙГ ЗОГСООХ',
      'windows_locked': 'Цонх цоожтой',
      'slide_to_start': 'Цэнэглэж эхлэхийн тулд гулсуулна уу',
      'slide_default': 'Эхлүүлэхийн тулд гулсуулна уу',
      'charging_receipt': 'Цэнэглэлтийн Баримт',
      'set_charge_limit': 'Цэнэглэх Хязгаар Тохируулах',
      'charging_station': 'Цэнэглэх станц',
      'charge_limit': 'Цэнэглэх хязгаар',
      'energy_delivered': 'Шилжүүлсэн эрчим хүч',
      'time_remaining': 'Үлдсэн хугацаа',
      'ocpp_log': 'OCPP лог',
      'nav_stations': 'Станц',
      'search_stations': 'Улаанбаатар дахь цэнэглэгч хайх...',
      'start_route': 'ЧИГЛЭЛ ЭХЛҮҮЛЭХ',
      'stop_route': 'ЧИГЛЭЛ ЗОГСООХ',
      'route_loading': 'Замыг тооцоолж байна...',
      'route_unavailable': 'Замын мэдээлэл авах боломжгүй. Чиглэлээр удирдана.',
      'navigating': 'НАВИГАЦИ ЯВАГДАЖ БАЙНА',
      'arrived_full': 'Цэнэглэх станцад хүрч ирлээ! QR кодыг уншуулна уу.',
      'arrived_short': 'Та очих газартаа ирлээ',
      'getting_directions': 'Чиглэл авч байна',
      'map_title': 'Цэнэглэх станцын зураг',
      'back': 'Буцах',
      'available': 'Сул байна',
      'kw_super': 'кВт Супер',
      'unit_km': 'км',
      'unit_kw': 'кВт',
      'unit_m': 'м',
      'unit_kmh': 'км/ц',
      'toward': 'чиглэлд',
      'dir_n': 'хойш',
      'dir_ne': 'зүүн хойш',
      'dir_e': 'зүүн',
      'dir_se': 'зүүн урагш',
      'dir_s': 'урагш',
      'dir_sw': 'баруун урагш',
      'dir_w': 'баруун',
      'dir_nw': 'баруун хойш',
      'logout_title': 'Гарах уу?',
      'logout_body': 'Та бүртгэлээсээ гарна. Дахин нэвтрэх шаардлагатай.',
      // Guest mode: browsing the network needs no account, charging does.
      'signin_required_charge': 'Цэнэглэхийн тулд нэвтэрнэ үү',
      'signin_required_wallet': 'Хэтэвчээ ашиглахын тулд нэвтэрнэ үү',
      'signin_required_history': 'Түүхээ харахын тулд нэвтэрнэ үү',
      'signin_required_vehicle': 'Машинаа харахын тулд нэвтэрнэ үү',
      'signin_required_controls': 'Удирдахын тулд нэвтэрнэ үү',
      'signin_required_account': 'Бүртгэлдээ нэвтэрнэ үү',
      'guest_vehicle_title': 'Машинаа холбоно уу',
      'guest_vehicle_body': 'Нэвтэрснээр цэнэглэлтийн явц, батарей, түгжээг эндээс хянана.',
      'guest_controls_title': 'Цэнэглэлтийн удирдлага',
      'guest_controls_body': 'Нэвтэрснээр цэнэглэлтээ эхлүүлж, зогсоох боломжтой.',
      'guest_browse_hint': 'Станцууд болон замыг нэвтрэхгүйгээр үзэх боломжтой.',
      'not_now': 'Одоо биш',
      'cancel': 'Цуцлах',
      'light_mode': 'Гэрэлтэй горим',
      'theme_dark_on': 'Бараан горим асаалаа',
      'theme_dark_off': 'Гэрэлтэй горим асаалаа',
      'or_login_with': 'Эсвэл дараах хаягаар нэвтрэх',
      'dont_have_account': 'Хаяггүй юу? Бүртгүүлэх',
      'already_have_account': 'Бүртгэлтэй юу? Нэвтрэх',
      'home': 'Нүүр',
      'stations': 'Станцууд',
      'map': 'Газрын зураг',
      'quick_controls': 'Түргэн удирдлага',
      'battery': 'Батерей',
      'remaining_km': 'Үлдсэн зайн хэмжээ',
      'charging': 'Цэнэглэж байна',
      'idle': 'Бэлэн',
      'scan_qr': 'QR код уншуулах',
      'ready_to_charge': 'Цэнэглэхэд бэлэн үү?',
      'scan_qr_desc': 'Цэнэглэгч дээрх QR кодыг уншуулж холбогдоно уу',
      'scan_button': 'QR КОД УНШУУЛАХ',
      'nearby_stations': 'Улаанбаатар дахь цэнэглэх станцууд',
      'power': 'Чадал',
      'vmax': 'Дээд хурд',
      'range': 'Зайн хэмжээ',
      'locked': 'Түгжигдсэн',
      'unlocked': 'Онгойлгосон',
      'dark': 'Бараан горим',
      'honk': 'Дохио өгөх',
      'control': 'Удирдлага',
      'energy': 'Эрчим хүч',
      'climate': 'Агааржуулагч',
      'media': 'Хөгжим',
      'tire_pressure': 'Дугуйн даралт',
      'location': 'Байршил',
      'last_known_location': 'Автомашины сүүлчийн байршил',
      'pay_and_start': '₮ ТӨЛӨӨД ЦЭНЭГЛЭЖ ЭХЛЭХ',
      'select_deposit': 'Цэнэглэх мөнгөн дүнг сонгоно уу:',
      'payment_method': 'Төлбөрийн хэрэгсэл:',
      'qpay': 'QPay (Үндэсний цахим төлбөр)',
      'card': 'Банкны карт (Голомт, Хаан)',
      // ---- Sign in / sign up ----
      'auth_login_headline': 'Дахин тавтай морил',
      'auth_login_sub': 'Утасны дугаар, PIN кодоороо нэвтэрнэ үү',
      'auth_register_headline': 'Бүртгэл үүсгэх',
      'auth_register_sub': 'Утасны дугаараа оруулаад SMS код авна уу',
      'auth_phone': 'Утасны дугаар',
      'auth_pin': 'PIN код',
      'auth_new_pin': '4 оронтой PIN код',
      'auth_confirm_pin': 'PIN кодоо давтана уу',
      'auth_code': '6 оронтой код',
      'forgot_pin': 'PIN код мартсан?',
      'link_open_failed': 'Холбоосыг нээж чадсангүй.',
      'auth_terms_prefix': 'Би ',
      'auth_terms_terms': 'Үйлчилгээний нөхцөл',
      'auth_terms_middle': ', ',
      // The accusative rides on the noun — `бодлого` + `ыг` is `бодлогыг`, not
      // `бодлого-ыг`. Keeping it inside the link also stops the line breaking
      // between a document's name and its case ending.
      'auth_terms_privacy': 'Нууцлалын бодлогыг',
      'auth_terms_suffix': ' зөвшөөрч байна',
      'auth_terms_required': 'Үргэлжлүүлэхийн тулд нөхцөлийг зөвшөөрнө үү',
      'auth_signing_in': 'Нэвтэрч байна',
      'auth_creating': 'Бүртгэж байна',
      'auth_sending': 'Илгээж байна',
      'auth_checking': 'Шалгаж байна',
      'auth_saving': 'Хадгалж байна',
      'auth_send_code': 'Код авах',
      'auth_verify_code': 'Үргэлжлүүлэх',
      'auth_save_pin': 'PIN код хадгалах',
      'auth_charge_label': 'БҮРТГЭЛИЙН ТҮВШИН',
      'auth_code_headline': 'Кодоо оруулна уу',
      'auth_code_sub': '{dest} дугаар руу 6 оронтой код илгээлээ',
      'auth_pin_headline': 'PIN код үүсгэх',
      'auth_pin_sub': 'Дараа нь утасны дугаар, энэ PIN кодоороо нэвтэрнэ',
      'auth_reset_headline': 'PIN кодоо сэргээх',
      'auth_reset_sub': 'Бүртгэлтэй дугаар руу тань SMS код илгээнэ',
      'auth_reset_pin_headline': 'Шинэ PIN код',
      'auth_reset_pin_sub': 'Энэ бүртгэлээр нэвтэрсэн бусад төхөөрөмжөөс гарна',
      'auth_resend': 'Код дахин авах',
      'auth_resend_in': '{s} секундын дараа дахин авах',
      'auth_change_number': 'Дугаар солих',
      'auth_back_to_login': 'Нэвтрэх рүү буцах',
      'auth_dev_code': 'Туршилтын код: {code}',
      'auth_required': 'Энэ талбарыг бөглөнө үү',
      'auth_bad_phone': 'Зөв утасны дугаар оруулна уу',
      'auth_bad_pin': '4 оронтой PIN код оруулна уу',
      'auth_bad_code': '6 оронтой кодоо оруулна уу',
      'auth_pin_mismatch': 'PIN код таарахгүй байна. Дахин оруулна уу',
      'auth_check_fields': 'Тэмдэглэсэн талбаруудаа шалгана уу',
      // ---- Account hub ----
      'nav_account': 'Бүртгэл',
      'filter_title': 'Станц шүүх',
      'filter_subtitle': 'Машиндаа тохирох цэнэглэгчийг олоорой',
      'filter_brand': 'Машины марк',
      'filter_brand_hint':
          'Маркаа сонгоход тохирох холбогч нь өөрөө сонгогдоно',
      'filter_connector': 'Холбогчийн төрөл',
      'filter_any_connector': 'Бүх холбогч',
      'filter_nearest': 'Хамгийн ойрыг олох',
      'filter_clear': 'Цэвэрлэх',
      'filter_apply': 'Хэрэглэх',
      'filter_none_match': 'Тохирох станц олдсонгүй. Шүүлтүүрээ өөрчилнө үү.',
      'loading': 'Ачаалж байна...',
      'stations_empty_title': 'Станцын мэдээлэл ачаалагдсангүй',
      'stations_empty_body':
          'Сүлжээгээ шалгаад дахин оролдоно уу. Холболт сэргэмэгц станцууд харагдана.',
      'stations_offline_notice':
          'Сүлжээ холбогдсонгүй — станцын мэдээлэл хуучирсан байж болно.',
      'filter_nearest_found': '{name} · {distance} км зайд',
      'filter_active': '{count} шүүлтүүр',
      'filter_showing': '{shown}/{total} станц',
      'acct_title': 'Миний бүртгэл',
      'acct_signed_in_as': '{email}-ээр нэвтэрсэн',
      'acct_status': 'Бүртгэлийн төлөв',
      'acct_verified': 'Баталгаажсан',
      'acct_not_verified': 'Баталгаажаагүй',
      'acct_email_label': 'И-мэйл хаяг',
      'acct_mobile_label': 'Гар утасны дугаар',
      'acct_no_number': 'Дугаар оруулаагүй байна',
      'acct_no_email': 'И-мэйл нэмээгүй',
      'acct_profile_title': 'Таны мэдээлэл',
      'acct_name_label': 'Нэр',
      'acct_save': 'Хадгалах',
      'acct_saved': 'Таны мэдээлэл хадгалагдлаа',
      'acct_nav_wallet': 'Хэтэвч',
      'acct_nav_wallet_sub': 'Үлдэгдэл, цэнэглэлт, хөдөлгөөн',
      'acct_nav_security': 'Аюулгүй байдал',
      'acct_nav_security_sub': 'Нууц үг, и-мэйл, утас баталгаажуулах',
      'acct_nav_sessions': 'Цэнэглэлтийн түүх',
      'acct_nav_sessions_sub': 'Өмнөх цэнэглэлт, баримт',
      'acct_idtags_title': 'Цэнэглэх картууд',
      'acct_idtags_body':
          'Цэнэглэх карт гэдэг нь цэнэглэгч таныг таних RFID карт эсвэл аппын код юм. Кодыг карт дээр хэвлэсэн байдаг.',
      'acct_idtags_none': 'Одоогоор холбосон карт алга байна.',
      'acct_idtags_add': 'Цэнэглэх карт нэмэх',
      'acct_idtags_hint':
          'Карт дээр хэвлэгдсэн кодыг яг байгаагаар нь оруулна уу.',
      'acct_idtags_submit': 'Карт холбох',
      'acct_idtags_unlink': 'Салгах',
      'acct_idtags_unlink_confirm': 'Энэ картыг салгах уу?',
      'acct_idtags_unlink_yes': 'Тийм, салгая',
      'acct_idtags_linked': '{tag} карт таны бүртгэлд холбогдлоо.',
      'acct_idtags_unlinked': '{tag} картын холбоос салгагдлаа.',

      // ---- Wallet ----
      'wallet_title': 'Хэтэвч',
      'wallet_subtitle':
          'QPay-ээр үлдэгдлээ цэнэглээд цэнэглэлтийн төлбөрөө автоматаар төлөөрэй.',
      'wallet_balance': 'Үлдэгдэл',
      'wallet_balance_hint': 'Цэнэглэлтэд зарцуулах боломжтой',
      'wallet_debt': 'Төлөх дүн',
      'wallet_debt_hint':
          'Цэнэглэлтийн төлбөр үлдэгдлээс давсан байна. Цэнэглэж төлнө үү.',
      'wallet_frozen': 'Энэ хэтэвч түр хаагдсан байна. Операторт хандана уу.',
      'wallet_topped_up': 'Нийт цэнэглэсэн',
      'wallet_spent': 'Нийт зарцуулсан',
      'wallet_linked_tags': 'Энэ үлдэгдлийг ашиглах картууд',
      'wallet_no_linked_tags':
          'Холбосон карт алга байна. Бүртгэл хэсгээс картаа холбоно уу.',
      'wallet_low_balance':
          'Таны үлдэгдэл {amount}-өөс бага байна. Цэнэглэхийн өмнө хэтэвчээ цэнэглэнэ үү.',
      'wallet_unavailable':
          'Хэтэвчийн үйлчилгээ түр боломжгүй байна. Хэсэг хугацааны дараа дахин оролдоно уу.',
      'wallet_history': 'Хэтэвчийн хөдөлгөөн',
      'wallet_history_empty': 'Одоогоор хөдөлгөөн алга байна.',
      'wallet_entry_topup': 'Цэнэглэлт',
      'wallet_entry_charge': 'Цэнэглэлтийн төлбөр',
      'wallet_entry_refund': 'Буцаалт',
      'wallet_entry_adjustment': 'Тохируулга',
      'wallet_entry_bonus': 'Урамшуулал',
      'wallet_balance_after': 'Үлдэгдэл: {balance}',
      'topup_title': 'Цэнэглэх',
      'topup_choose': 'Дүнгээ сонгоно уу',
      'topup_custom': 'Эсвэл дүнгээ оруулна уу',
      'topup_amount_label': 'Дүн (₮)',
      'topup_range': '{min} – {max} хооронд',
      'topup_submit': 'Цэнэглэх',
      'topup_submitting': 'Нэхэмжлэх үүсгэж байна…',
      'topup_invalid': 'Дүнгээ оруулна уу',
      'topup_disabled': 'Цэнэглэх үйлчилгээ түр боломжгүй байна.',
      'invoice_title': 'Уншуулж төлнө үү',
      'invoice_amount': 'Төлөх дүн',
      'invoice_instruction':
          'QR кодыг банкны аппаараа уншуулах эсвэл доороос банкаа сонгоно уу.',
      'invoice_open_bank': 'Банкны апп нээх',
      'invoice_waiting': 'Төлбөр хүлээж байна…',
      'invoice_check': 'Төлбөрөө хийсэн',
      'invoice_checking': 'Шалгаж байна…',
      'invoice_paid': '{amount} таны хэтэвчид нэмэгдлээ.',
      'invoice_expired':
          'Энэ нэхэмжлэхийн хугацаа дууссан байна. Дахин эхлүүлнэ үү.',
      'invoice_not_paid':
          'Төлбөр хараахан ирээгүй байна. Түр хүлээгээд дахин шалгана уу.',
      'invoice_canceled': 'Энэ нэхэмжлэх цуцлагдсан байна.',
      'invoice_start_over': 'Өөр дүнгээр цэнэглэх',
      'invoice_timed_out':
          'Төлбөрийг удаан хүлээлээ. Төлсөн бол «Төлбөрөө хийсэн» товчийг дарна уу.',
      'invoice_open_link': 'Төлбөрийн холбоос нээх',

      // ---- Charging history ----
      'sess_title': 'Цэнэглэлтийн түүх',
      'sess_empty':
          'Бүртгэлдээ цэнэглэх карт холбож, цэнэглэгч дээр ашигласны дараа цэнэглэлтийн түүх энд харагдана.',
      'sess_unavailable':
          'Цэнэглэх сүлжээтэй одоохондоо холбогдож чадсангүй тул таны цэнэглэлтүүд харагдахгүй байна.',
      'sess_count': '{count} цэнэглэлт',
      'sess_connector': '{id}-р холбогч',
      'sess_started': 'Эхэлсэн',
      'sess_duration': 'Үргэлжлэх хугацаа',
      'sess_energy': 'Эрчим хүч',
      'sess_cost': 'Төлбөр',
      'sess_in_progress': 'Үргэлжилж байна',
      'sess_completed': 'Дууссан',
      'sess_rejected': 'Татгалзсан',
      'sess_stop': 'Зогсоох',
      'sess_stopping': 'Зогсоож байна…',
      'sess_stop_confirm': 'Энэ цэнэглэлтийг зогсоох уу?',
      'sess_stop_yes': 'Тийм, зогсооё',
      'sess_keep': 'Үргэлжлүүлэх',
      'sess_stop_accepted':
          'Зогсоох хүсэлтийг хүлээн авлаа. Цэнэглэгч цэнэглэлтийг дуусгаж байна.',
      'sess_stop_replied': 'Цэнэглэгч «{status}» гэж хариулав.',

      // ---- Security ----
      'sec_title': 'Аюулгүй байдал',
      'sec_pin_title': 'PIN код',
      'sec_pin_current': 'Одоогийн PIN код',
      'sec_pin_new': 'Шинэ PIN код',
      'sec_pin_confirm': 'Шинэ PIN кодоо давтах',
      'sec_pin_change': 'PIN код солих',
      'sec_pin_set': 'PIN код тохируулах',
      'sec_pin_changed':
          'PIN код тань солигдлоо. Бусад төхөөрөмжөөс гарсан байна.',
      'sec_pin_hint': 'PIN кодоо солиход бусад төхөөрөмжөөс гарна.',
      'sec_pin_none':
          'Энэ бүртгэлд PIN код алга. Утасны дугаараараа нэвтрэхийн тулд тохируулна уу.',
      'sec_email_none': 'И-мэйл хаяг нэмээгүй байна.',
      'sec_email_title': 'И-мэйл хаяг',
      'sec_email_confirmed':
          '{email} баталгаажсан байна. Үүгээр цэнэглэлтийн баримт илгээнэ.',
      'sec_email_pending':
          '{email} хаягаа баталгаажуулна уу. Илгээх холбоос 24 цагийн турш хүчинтэй.',
      'sec_resend_email': 'Баталгаажуулах и-мэйл дахин илгээх',
      'sec_sent_to': '{dest} руу илгээлээ',
      'sec_phone_title': 'Гар утасны дугаар',
      'sec_phone_confirmed': '{phone} баталгаажсан байна.',
      'sec_phone_pending':
          'Дугаараа баталгаажуулбал цэнэглэлтийн мэдэгдэл, PIN код сэргээх код авах боломжтой.',
      'sec_send_code': 'Код илгээх',
      'sec_code_label': '6 оронтой код',
      'sec_verify': 'Баталгаажуулах',
      'sec_phone_done': 'Утасны дугаар баталгаажлаа.',
      'sec_delete_title': 'Акаунт болон мэдээлэл устгах',
      'sec_delete_body': 'Та акаунтоо устгаснаар өөрийн профайл, холбосон RFID карт болон хувийн мэдээллээ бүрмөсөн устгах болно.',
      'sec_delete_btn': 'Акаунт устгах',
      'sec_delete_confirm_title': 'Акаунт устгах уу?',
      'sec_delete_confirm_body': 'Энэ үйлдэл буцах боломжгүй бөгөөд таны Eplug акаунт ба холбогдох хувийн мэдээлэл бүрмөсөн устгагдана.',
      'sec_delete_success': 'Таны акаунт амжилттай устгагдлаа.',

      // ---- Shared ----
      'retry': 'Дахин оролдох',
      'save': 'Хадгалах',
    },
    'en': {
      'appName': 'Eplug',
      'tagline': 'Mongolia\'s Premier EV Charging Network',
      'slideshow1_title': 'Ulaanbaatar Fast Chargers',
      'slideshow1_sub': 'Ultra-fast chargers up to 200 kW in UB',
      'slideshow2_title': 'Smart & Seamless Payment',
      'slideshow2_sub': 'Scan QR Code and pay instantly via QPay or Card',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Log out',
      'activity_title': 'Activity',
      'activity_subtitle': 'Your charging history',
      'activity_empty': 'Nothing recorded yet',
      'activity_details': 'Technical details',
      'act_authorize': 'Authorised',
      'act_start': 'Charging started',
      'act_stop': 'Charging finished',
      'act_meter': 'Meter reading recorded',
      'act_status': 'Status updated',
      'act_heartbeat': 'Connection checked',
      'act_boot': 'Station connected',
      'act_remote_start': 'Started remotely',
      'act_remote_stop': 'Stopped remotely',
      'act_reserve': 'Reservation recorded',
      'act_other': 'Station event',
      'clear_history': 'Clear history',
      'media_artist': 'Folk Music Ensemble',
      'media_track': 'Shangri-La Melody',
      'media_system': 'Dolby Atmos system',
      'download_receipt': 'RECEIPT',
      'done': 'DONE',
      'outside_temp': 'Outside temperature',
      'tx_ref': 'Transaction ref',
      'connector_speed': 'Connector / Speed',
      'receipt_emailed': 'Receipt sent by email.',
      'total_paid': 'Total Paid',
      'total_cost': 'Total cost',
      'unit_price': 'Unit price',
      'added_range': 'Added range',
      'last_measured': 'Last measured',
      'estimated_total': 'Estimated total',
      'payment_ok': 'Payment complete. Charging started',
      'confirm_payment': 'Confirm payment',
      'scanning': 'SCANNING...',
      'vehicle_location': 'Vehicle location in Ulaanbaatar',
      'vehicle_location_hint': 'Tap to open the interactive map',
      'limit_label': 'Limit',
      'charging_now': 'CHARGING',
      'stop_charging': 'STOP CHARGING',
      'windows_locked': 'Windows locked',
      'slide_to_start': 'Slide to start charging',
      'slide_default': 'Slide to start',
      'charging_receipt': 'Charging Receipt',
      'set_charge_limit': 'Set Charge Limit',
      'charging_station': 'Charging station',
      'charge_limit': 'Charge limit',
      'energy_delivered': 'Energy delivered',
      'time_remaining': 'Time remaining',
      'ocpp_log': 'OCPP log',
      'nav_stations': 'Stations',
      'search_stations': 'Search chargers in Ulaanbaatar...',
      'start_route': 'START ROUTE',
      'stop_route': 'STOP ROUTE',
      'route_loading': 'Calculating route...',
      'route_unavailable': 'Road route unavailable. Guiding by direction.',
      'navigating': 'NAVIGATING',
      'arrived_full': 'You have arrived. Scan the QR code to begin.',
      'arrived_short': 'You have arrived',
      'getting_directions': 'Getting directions',
      'map_title': 'Charging station map',
      'back': 'Back',
      'available': 'available',
      'kw_super': 'kW Super',
      'unit_km': 'km',
      'unit_kw': 'kW',
      'unit_m': 'm',
      'unit_kmh': 'km/h',
      'toward': 'to the',
      'dir_n': 'north',
      'dir_ne': 'north-east',
      'dir_e': 'east',
      'dir_se': 'south-east',
      'dir_s': 'south',
      'dir_sw': 'south-west',
      'dir_w': 'west',
      'dir_nw': 'north-west',
      'logout_title': 'Log out?',
      'logout_body': 'You will be signed out and need to log in again.',
      // Guest mode: browsing the network needs no account, charging does.
      'signin_required_charge': 'Sign in to start charging',
      'signin_required_wallet': 'Sign in to use your wallet',
      'signin_required_history': 'Sign in to see your history',
      'signin_required_vehicle': 'Sign in to see your vehicle',
      'signin_required_controls': 'Sign in to control charging',
      'signin_required_account': 'Sign in to your account',
      'guest_vehicle_title': 'Connect your vehicle',
      'guest_vehicle_body': 'Sign in to follow charging progress, battery and lock status here.',
      'guest_controls_title': 'Charging controls',
      'guest_controls_body': 'Sign in to start and stop a charge from your phone.',
      'guest_browse_hint': 'Stations and routes are free to browse without an account.',
      'not_now': 'Not now',
      'cancel': 'Cancel',
      'light_mode': 'Light Mode',
      'theme_dark_on': 'Dark mode on',
      'theme_dark_off': 'Light mode on',
      'or_login_with': 'Or continue with',
      'dont_have_account': 'Don\'t have an account? Register',
      'already_have_account': 'Already registered? Login',
      'home': 'Home',
      'stations': 'Stations',
      'map': 'Map',
      'quick_controls': 'Quick Controls',
      'battery': 'Battery',
      'remaining_km': 'Remaining Range',
      'charging': 'Charging',
      'idle': 'Standby',
      'scan_qr': 'Scan QR Code',
      'ready_to_charge': 'Ready to Charge?',
      'scan_qr_desc': 'Scan the station QR code to unlock plug & pay',
      'scan_button': 'SCAN QR CODE & START',
      'nearby_stations': 'Charging Stations in Ulaanbaatar',
      'power': 'Power',
      'vmax': 'Vmax',
      'range': 'Range',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'dark': 'Dark Mode',
      'honk': 'Sound Horn',
      'control': 'Controls',
      'energy': 'Energy',
      'climate': 'Climate',
      'media': 'Media',
      'tire_pressure': 'Tire Pressure',
      'location': 'Location',
      'last_known_location': 'Vehicle\'s Last Known Location',
      'pay_and_start': 'PAY & START CHARGING',
      'select_deposit': 'Select Charging Amount:',
      'payment_method': 'Payment Method:',
      'qpay': 'QPay (National Mobile Pay)',
      'card': 'Bank Card (Golomt / Khan Bank)',
      // ---- Sign in / sign up ----
      'auth_login_headline': 'Welcome back',
      'auth_login_sub': 'Sign in with your phone number and PIN',
      'auth_register_headline': 'Create your account',
      'auth_register_sub': 'Enter your phone number and we will text you a code',
      'auth_phone': 'Phone number',
      'auth_pin': 'PIN code',
      'auth_new_pin': '4-digit PIN',
      'auth_confirm_pin': 'Repeat the PIN',
      'auth_code': '6-digit code',
      'forgot_pin': 'Forgot PIN?',
      'link_open_failed': 'Could not open the link.',
      'auth_terms_prefix': 'I accept the ',
      'auth_terms_terms': 'Terms of Service',
      'auth_terms_middle': ' and ',
      'auth_terms_privacy': 'Privacy Policy',
      'auth_terms_suffix': '',
      'auth_terms_required': 'Accept the terms to continue',
      'auth_signing_in': 'Signing in',
      'auth_creating': 'Creating account',
      'auth_sending': 'Sending',
      'auth_checking': 'Checking',
      'auth_saving': 'Saving',
      'auth_send_code': 'Send code',
      'auth_verify_code': 'Continue',
      'auth_save_pin': 'Save PIN',
      'auth_charge_label': 'PROFILE CHARGE',
      'auth_code_headline': 'Enter the code',
      'auth_code_sub': 'We texted a 6-digit code to {dest}',
      'auth_pin_headline': 'Create your PIN',
      'auth_pin_sub': 'You will sign in with your phone number and this PIN',
      'auth_reset_headline': 'Reset your PIN',
      'auth_reset_sub': 'We will text a code to your registered number',
      'auth_reset_pin_headline': 'Choose a new PIN',
      'auth_reset_pin_sub':
          'Other devices signed in to this account will be signed out',
      'auth_resend': 'Resend code',
      'auth_resend_in': 'Resend in {s}s',
      'auth_change_number': 'Change number',
      'auth_back_to_login': 'Back to sign in',
      'auth_dev_code': 'Dev code: {code}',
      'auth_required': 'Fill in this field',
      'auth_bad_phone': 'Enter a valid phone number',
      'auth_bad_pin': 'Enter a 4-digit PIN',
      'auth_bad_code': 'Enter the 6-digit code',
      'auth_pin_mismatch': 'The PINs do not match. Type it again',
      'auth_check_fields': 'Check the highlighted fields',
      // ---- Account hub ----
      'nav_account': 'Account',
      'filter_title': 'Filter stations',
      'filter_subtitle': 'Find a charger that fits your car',
      'filter_brand': 'Car brand',
      'filter_brand_hint': 'Picking a brand selects the plugs it charges on',
      'filter_connector': 'Connector type',
      'filter_any_connector': 'All connectors',
      'filter_nearest': 'Find nearest',
      'filter_clear': 'Clear',
      'filter_apply': 'Apply',
      'filter_none_match': 'No station matches. Try changing the filter.',
      'loading': 'Loading...',
      'stations_empty_title': 'Stations could not be loaded',
      'stations_empty_body':
          'Check your connection and try again. Stations appear as soon as the network is reachable.',
      'stations_offline_notice': 'Offline — these stations may be out of date.',
      'filter_nearest_found': '{name} · {distance} km away',
      'filter_active': '{count} filters',
      'filter_showing': '{shown}/{total} stations',
      'acct_title': 'My account',
      'acct_signed_in_as': 'Signed in as {email}',
      'acct_status': 'Account status',
      'acct_verified': 'Verified',
      'acct_not_verified': 'Not verified',
      'acct_email_label': 'Email address',
      'acct_mobile_label': 'Mobile number',
      'acct_no_number': 'No number yet',
      'acct_no_email': 'No email yet',
      'acct_profile_title': 'Your details',
      'acct_name_label': 'Name',
      'acct_save': 'Save changes',
      'acct_saved': 'Your details are saved',
      'acct_nav_wallet': 'Wallet',
      'acct_nav_wallet_sub': 'Balance, top-ups and activity',
      'acct_nav_security': 'Security',
      'acct_nav_security_sub': 'Password, email and phone',
      'acct_nav_sessions': 'Charging history',
      'acct_nav_sessions_sub': 'Past sessions and receipts',
      'acct_idtags_title': 'Charge tags',
      'acct_idtags_body':
          'A charge tag is the RFID card or app code a charger uses to recognise you. The operator issues it and prints the code on the card.',
      'acct_idtags_none': 'No charge tag linked yet.',
      'acct_idtags_add': 'Add a charge tag',
      'acct_idtags_hint': 'Enter the code exactly as printed on the card.',
      'acct_idtags_submit': 'Link tag',
      'acct_idtags_unlink': 'Unlink',
      'acct_idtags_unlink_confirm': 'Unlink this tag?',
      'acct_idtags_unlink_yes': 'Yes, unlink',
      'acct_idtags_linked': 'Charge tag {tag} is linked to your account.',
      'acct_idtags_unlinked': 'Charge tag {tag} is no longer linked.',

      // ---- Wallet ----
      'wallet_title': 'Wallet',
      'wallet_subtitle':
          'Top up with QPay and each session is paid from your balance automatically.',
      'wallet_balance': 'Balance',
      'wallet_balance_hint': 'Available to spend on charging',
      'wallet_debt': 'Amount owed',
      'wallet_debt_hint':
          'A session cost more than your balance. Top up to settle it.',
      'wallet_frozen': 'This wallet is frozen. Please contact the operator.',
      'wallet_topped_up': 'Topped up',
      'wallet_spent': 'Spent',
      'wallet_linked_tags': 'Tags that spend this balance',
      'wallet_no_linked_tags': 'No tag linked. Link one from your account.',
      'wallet_low_balance':
          'Your balance is under {amount}. Top up before you charge.',
      'wallet_unavailable':
          'The wallet service is not available right now. Please try again shortly.',
      'wallet_history': 'Wallet activity',
      'wallet_history_empty': 'No wallet activity yet.',
      'wallet_entry_topup': 'Top-up',
      'wallet_entry_charge': 'Charging',
      'wallet_entry_refund': 'Refund',
      'wallet_entry_adjustment': 'Adjustment',
      'wallet_entry_bonus': 'Bonus',
      'wallet_balance_after': 'Balance: {balance}',
      'topup_title': 'Top up',
      'topup_choose': 'Choose an amount',
      'topup_custom': 'Or enter your own',
      'topup_amount_label': 'Amount (₮)',
      'topup_range': 'Between {min} and {max}',
      'topup_submit': 'Top up',
      'topup_submitting': 'Creating invoice…',
      'topup_invalid': 'Enter an amount',
      'topup_disabled': 'Top-ups are unavailable right now.',
      'invoice_title': 'Scan to pay',
      'invoice_amount': 'Amount due',
      'invoice_instruction':
          'Scan the QR with your banking app, or pick your bank below.',
      'invoice_open_bank': 'Open bank app',
      'invoice_waiting': 'Waiting for payment…',
      'invoice_check': "I've paid",
      'invoice_checking': 'Checking…',
      'invoice_paid': '{amount} has been added to your wallet.',
      'invoice_expired': 'This invoice has expired. Start again.',
      'invoice_not_paid': 'No payment yet. Wait a moment and check again.',
      'invoice_canceled': 'This invoice was cancelled.',
      'invoice_start_over': 'Top up a different amount',
      'invoice_timed_out':
          'We stopped waiting for payment. If you have paid, tap "I\'ve paid".',
      'invoice_open_link': 'Open payment link',

      // ---- Charging history ----
      'sess_title': 'Charging history',
      'sess_empty':
          'Your charging history appears here once a charge tag is linked to your account and used at a charger.',
      'sess_unavailable':
          'We could not reach the charging network just now, so your sessions are not shown.',
      'sess_count': '{count} sessions',
      'sess_connector': 'Connector {id}',
      'sess_started': 'Started',
      'sess_duration': 'Duration',
      'sess_energy': 'Energy',
      'sess_cost': 'Cost',
      'sess_in_progress': 'In progress',
      'sess_completed': 'Completed',
      'sess_rejected': 'Rejected',
      'sess_stop': 'Stop',
      'sess_stopping': 'Stopping…',
      'sess_stop_confirm': 'Stop this charging session?',
      'sess_stop_yes': 'Yes, stop it',
      'sess_keep': 'Keep charging',
      'sess_stop_accepted':
          'Stop request accepted. The charger is ending the session.',
      'sess_stop_replied': 'The charger replied "{status}".',

      // ---- Security ----
      'sec_title': 'Security',
      'sec_pin_title': 'PIN code',
      'sec_pin_current': 'Current PIN',
      'sec_pin_new': 'New PIN',
      'sec_pin_confirm': 'Repeat the new PIN',
      'sec_pin_change': 'Change PIN',
      'sec_pin_set': 'Set PIN',
      'sec_pin_changed':
          'Your PIN is changed. Other devices have been signed out.',
      'sec_pin_hint': 'Changing your PIN signs out your other devices.',
      'sec_pin_none':
          'This account has no PIN yet. Set one to sign in with your phone number.',
      'sec_email_none': 'No email address added.',
      'sec_email_title': 'Email address',
      'sec_email_confirmed':
          '{email} is confirmed. We send charging receipts there.',
      'sec_email_pending':
          'Confirm {email}. The link we email is valid for 24 hours.',
      'sec_resend_email': 'Resend the confirmation email',
      'sec_sent_to': 'Sent to {dest}',
      'sec_phone_title': 'Mobile number',
      'sec_phone_confirmed': '{phone} is confirmed.',
      'sec_phone_pending':
          'Confirm your number to get charging notices and PIN reset codes.',
      'sec_send_code': 'Send code',
      'sec_code_label': '6-digit code',
      'sec_verify': 'Confirm',
      'sec_phone_done': 'Your number is confirmed.',
      'sec_delete_title': 'Delete Account & Data',
      'sec_delete_body': 'Deleting your account will permanently remove your profile, linked RFID tags, and personal data.',
      'sec_delete_btn': 'Delete Account',
      'sec_delete_confirm_title': 'Delete account?',
      'sec_delete_confirm_body': 'This action cannot be undone. Your Eplug account and all associated personal data will be permanently removed.',
      'sec_delete_success': 'Your account has been deleted successfully.',

      // ---- Shared ----
      'retry': 'Try again',
      'save': 'Save',
    },
  };

  static String get(String key) {
    final langCode = currentLanguage == AppLanguage.mn ? 'mn' : 'en';
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
