enum AppLanguage { mn, en }

class AppStrings {
  static AppLanguage currentLanguage = AppLanguage.mn;

  static const Map<String, Map<String, String>> _localizedValues = {
    'mn': {
      'appName': 'Zev Charger',
      'tagline': 'Монголын Анхны Сүлжээ Цэнэглэгч',
      'slideshow1_title': 'Улаанбаатар хотын EV Цэнэглэгч',
      'slideshow1_sub': 'Хамгийн хурдан 200 кВт хүртэлх супер цэнэглэгч',
      'slideshow2_title': 'Ухаалаг & Хялбар Төлбөр',
      'slideshow2_sub': 'QR код уншуулаад QPay / Картаар шууд төлнө',
      'login': 'Нэвтрэх',
      'register': 'Бүртгүүлэх',
      'phone_email': 'Утасны дугаар эсвэл И-мэйл',
      'password': 'Нууц үг',
      'forgot_password': 'Нууц үг мартсан?',
      'or_login_with': 'Эсвэл дараах хаягаар нэвтрэх',
      'dont_have_account': 'Хаяггүй юу? Бүртгүүлэх',
      'already_have_account': 'Бүртгэлтэй юу? Нэвтрэх',
      'home': 'Нүүр',
      'stations': 'Станцууд',
      'map': 'Газрын зураг',
      'quick_controls': 'Түргэн удирдлага',
      'battery': 'Батерей',
      'remaining_km': 'Үлдсэн зайн хэмжээ',
      'charging': 'Цэнэглэж байна',
      'idle': 'Бэлэн',
      'scan_qr': 'QR код уншуулах',
      'ready_to_charge': 'Цэнэглэхэд бэлэн үү?',
      'scan_qr_desc': 'Цэнэглэгч дээрх QR кодыг уншуулж холбогдоно уу',
      'scan_button': 'QR КОД УНШУУЛАХ',
      'nearby_stations': 'Улаанбаатар дахь цэнэглэх станцууд',
      'power': 'Чадал',
      'vmax': 'Дээд хурд',
      'range': 'Зайн хэмжээ',
      'locked': 'Түгжигдсэн',
      'unlocked': 'Онгойлгосон',
      'dark': 'Бараан горим',
      'honk': 'Дохио өгөх',
      'control': 'Удирдлага',
      'energy': 'Эрчим хүч',
      'climate': 'Агааржуулагч',
      'media': 'Хөгжим',
      'tire_pressure': 'Дугуйн даралт',
      'location': 'Байршил',
      'last_known_location': 'Автомашины сүүлчийн байршил',
      'pay_and_start': '₮ ТӨЛӨӨД ЦЭНЭГЛЭЖ ЭХЛЭХ',
      'select_deposit': 'Цэнэглэх мөнгөн дүнг сонгоно уу:',
      'payment_method': 'Төлбөрийн хэрэгсэл:',
      'qpay': 'QPay (Үндэсний цахим төлбөр)',
      'card': 'Банкны карт (Голомт, Хаан)',
    },
    'en': {
      'appName': 'Zev Charger',
      'tagline': 'Mongolia\'s Premier EV Charging Network',
      'slideshow1_title': 'Ulaanbaatar Fast Chargers',
      'slideshow1_sub': 'Ultra-fast chargers up to 200 kW in UB',
      'slideshow2_title': 'Smart & Seamless Payment',
      'slideshow2_sub': 'Scan QR Code and pay instantly via QPay or Card',
      'login': 'Login',
      'register': 'Register',
      'phone_email': 'Phone Number or Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'or_login_with': 'Or continue with',
      'dont_have_account': 'Don\'t have an account? Register',
      'already_have_account': 'Already registered? Login',
      'home': 'Home',
      'stations': 'Stations',
      'map': 'Map',
      'quick_controls': 'Quick Controls',
      'battery': 'Battery',
      'remaining_km': 'Remaining Range',
      'charging': 'Charging',
      'idle': 'Standby',
      'scan_qr': 'Scan QR Code',
      'ready_to_charge': 'Ready to Charge?',
      'scan_qr_desc': 'Scan the station QR code to unlock plug & pay',
      'scan_button': 'SCAN QR CODE & START',
      'nearby_stations': 'Charging Stations in Ulaanbaatar',
      'power': 'Power',
      'vmax': 'Vmax',
      'range': 'Range',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'dark': 'Dark Mode',
      'honk': 'Sound Horn',
      'control': 'Controls',
      'energy': 'Energy',
      'climate': 'Climate',
      'media': 'Media',
      'tire_pressure': 'Tire Pressure',
      'location': 'Location',
      'last_known_location': 'Vehicle\'s Last Known Location',
      'pay_and_start': 'PAY & START CHARGING',
      'select_deposit': 'Select Charging Amount:',
      'payment_method': 'Payment Method:',
      'qpay': 'QPay (National Mobile Pay)',
      'card': 'Bank Card (Golomt / Khan Bank)',
    },
  };

  static String get(String key) {
    final langCode = currentLanguage == AppLanguage.mn ? 'mn' : 'en';
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
